import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    price: "200",
    categoryName: "finance",
    src: "https://images-na.ssl-images-amazon.com/images/I/51u8ZRDCVoL._SX330_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "The Psychology of Money",
    author: "Morgan Housel",
    price: "250",
    categoryName: "finance",
    src: "https://images-na.ssl-images-amazon.com/images/I/41r6F2LRf8L._SX323_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "The Intelligent Investor",
    author: "Benjamin Graham",
    price: "450",
    categoryName: "finance",
    src: "https://images-na.ssl-images-amazon.com/images/I/51DLoxAJ68L._SX324_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "Diamonds in the Dust",
    author: "Saurabh Mukherjea",
    price: "320",
    categoryName: "finance",
    src: "https://images-na.ssl-images-amazon.com/images/I/41k0WnFsBGL._SX318_BO1,204,203,200_.jpg ",
  },
  {
    _id: uuid(),
    title: "Coffee Can Investing",
    author: "Saurabh Mukherjea",
    price: "320",
    categoryName: "finance",
    src: "https://images-na.ssl-images-amazon.com/images/I/51w5fy6w2zL._SX312_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "Ikigai",
    author: "Hector Garcia",
    price: "300",
    categoryName: "self help",
    src: "https://images-na.ssl-images-amazon.com/images/I/51T8OXMiB5L._SX356_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "The Courage To Be Disliked",
    author: "Ichiro Kishimi",
    price: "277",
    categoryName: "self help",
    src: "https://images-na.ssl-images-amazon.com/images/I/51kBS7Szd4L._SX324_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "The Almanack Of Naval Ravikant",
    author: "Eric Jorgenson",
    price: "270",
    categoryName: "self help",
    src: "https://images-na.ssl-images-amazon.com/images/I/31bDtgec8NL._SX324_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: "206",
    categoryName: "self help",
    src: "https://images-na.ssl-images-amazon.com/images/I/410llGwMZGL._SX328_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "It Ends With Us",
    author: "Colleen Hoover",
    price: "450",
    categoryName: "romance",
    src: "https://images-na.ssl-images-amazon.com/images/I/51qX2RGyhhL._SX320_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "The Spanish Love Deception",
    author: "Elena Armas",
    price: "350",
    categoryName: "romance",
    src: "https://images-na.ssl-images-amazon.com/images/I/41VJeilkF4L._SX320_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "The Hating Game",
    author: "Sally Thorne",
    price: "500",
    categoryName: "romance",
    src: "https://images-na.ssl-images-amazon.com/images/I/51vAB4b4JwL._SX315_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "It Happened One Summer",
    author: "Tessa Bailey",
    price: "250",
    categoryName: "romance",
    src: "https://images-na.ssl-images-amazon.com/images/I/51Io3NB1qDL._SX329_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "We Were Liars",
    author: "E. Lockhart",
    price: "350",
    categoryName: "romance",
    src: "https://images-na.ssl-images-amazon.com/images/I/619nhWVHi-L.jpg",
  },
  {
    _id: uuid(),
    title: "The Silent Patient",
    author: "Alex Michaelides",
    price: "215",
    categoryName: "thriller",
    src: "https://images-na.ssl-images-amazon.com/images/I/51OuP0mmnwL._SX322_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    price: "194",
    categoryName: "thriller",
    src: "https://images-na.ssl-images-amazon.com/images/I/41s25iwW7zS._SX319_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "Misery",
    author: "Stephen King",
    price: "450",
    categoryName: "thriller",
    src: "https://images-na.ssl-images-amazon.com/images/I/51iKRax-QFL._SX324_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "Gone Girl",
    author: "Gillian Flynn",
    price: "349",
    categoryName: "thriller",
    src: "https://images-na.ssl-images-amazon.com/images/I/41oR8CLl6lL._SX323_BO1,204,203,200_.jpg",
  },
  {
    _id: uuid(),
    title: "Verity",
    author: "Colleen Hoover",
    price: "299",
    categoryName: "thriller",
    src: "https://images-na.ssl-images-amazon.com/images/I/410i2hlkSLL._SX322_BO1,204,203,200_.jpg",
  },
];
